# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.chrome.service import Service as ChromeService
class TestGoogle():

  def setup_method(self, method):
    chrome_path = '/Users/alikson/Downloads/chromedriver-mac-x64/chromedriver'
    service = ChromeService(executable_path=chrome_path)
    self.driver = webdriver.Chrome(service=service)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_google(self):
    self.driver.get("https://www.google.com//search?q=palmeiras&sca_esv=589119146&sxsrf=AM9HkKnD_jK03VgoMLxrLyXWCkKFjh7wTw%3A1702058844218&source=hp&ei=XFtzZbz3CunW1sQPnuyBiAQ&iflsig=AO6bgOgAAAAAZXNpbGReGK7LMAW-82sjXazR_YT1rUdG&ved=0ahUKEwi8la2mt4CDAxVpq5UCHR52AEEQ4dUDCAo&uact=5&oq=palmeiras&gs_lp=Egdnd3Mtd2l6IglwYWxtZWlyYXMyDxAjGIAEGIoFGCcYRhj9ATINEC4YQxixAxiABBiKBTINEAAYgAQYigUYQxixAzIIEAAYgAQYsQMyBRAAGIAEMhAQABiABBiKBRhDGLEDGIMBMg0QABiABBiKBRhDGLEDMgUQABiABDIOEAAYgAQYigUYsQMYgwEyCxAAGIAEGLEDGIMBSPwOUABYtAhwAHgAkAEAmAHcAaAB5wqqAQUwLjguMbgBA8gBAPgBAcICChAjGIAEGIoFGCfCAgQQIxgnwgIIEC4YgAQYsQPCAgsQLhiABBjHARjRA8ICDRAuGIAEGIoFGEMYsQPCAhEQLhiABBixAxiDARjHARjRA8ICFhAuGIAEGIoFGEMYsQMYgwEYxwEY0QPCAgoQABiABBiKBRhD&sclient=gws-wiz")
    self.driver.set_window_size(1280, 696)
    self.driver.execute_script("window.scrollTo(0,174)")
    self.driver.execute_script("window.scrollTo(0,1122)")
  
