version: '3.3'

services:
  # Banco de dados Postggresql
  db:
    image: postgres:alpine
    container_name: bibpub-postgres
    restart: always
    environment:
      - POSTGRES_DB=bibpubdb 
      - POSTGRES_USER=bibpub 
      - POSTGRES_PASSWORD=@dm1n
      - LANG=pt_BR.UTF8 
      - PGDATA=/var/lib/postgresql/data 
    ports:
      5432:5432
    volumes:
      postgres_data:/var/lib/postgresql/data 
    copy:
      - .scripts/carga_tb_autor.sql:/docker-entrypoint-initdb.d/carga_tb_autor.sql
      - .scripts/carga_tb_editora.sql:/docker-entrypoint-initdb.d/carga_tb_editora.sql
      - .scripts/carga_tb_categoria.sql:/docker-entrypoint-initdb.d/carga_tb_categoria.sql
      - .scripts/carga_tb_obra.sql:/docker-entrypoint-initdb.d/carga_tb_obra.sql
      - .scripts/carga_tb_pais.sql:/docker-entrypoint-initdb.d/carga_tb_pais.sql
      - .scripts/carga_tb_pessoa.sql:/docker-entrypoint-initdb.d/carga_tb_pessoa.sql
      - .scripts/carga_tb_unidade.sql:/docker-entrypoint-initdb.d/carga_tb_unidade.sql

  # Aplicação web
  web:
    build: .
    #command: ["./bibpub_web.sh"]
    command: python manage.py runserver 0.0.0.0:8000
    container_name: bibpub-web
    volumes:
      - .:/bibpub
    ports:
      - "8000"
    links:
      - db
    depends_on:
      - db 

  # Volumes
  volumes:
    postgres-data: