# Generated by Django 4.1.5 on 2023-11-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibpub", "0002_alter_categoria_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={
                "permissions": [
                    ("can_view_categoria", "Can view categorias"),
                    ("can_change_categoria", "Can change categorias"),
                    ("can_add_categoria", "Can add categorias"),
                    ("can_delete_categoria", "Can delete categorias"),
                ],
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.AlterField(
            model_name="categoria",
            name="descricao",
            field=models.TextField(unique=True, verbose_name="Descrição"),
        ),
    ]
