# Generated by Django 4.2.7 on 2023-11-17 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bibpub', '0004_autor_editora_pessoa_alter_categoria_table_obra_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'permissions': [('can_view_autor', 'Can view autores'), ('can_change_autor', 'Can change autores'), ('can_add_autor', 'Can add autores'), ('can_delete_autor', 'Can delete autores')], 'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='editora',
            options={'permissions': [('can_view_autor', 'Can view autores'), ('can_change_autor', 'Can change autores'), ('can_add_autor', 'Can add autores'), ('can_delete_autor', 'Can delete autores')], 'verbose_name': 'Editora', 'verbose_name_plural': 'Editoras'},
        ),
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'permissions': [('can_view_autor', 'Can view autores'), ('can_change_autor', 'Can change autores'), ('can_add_autor', 'Can add autores'), ('can_delete_autor', 'Can delete autores')], 'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimos'},
        ),
        migrations.AlterModelOptions(
            name='obra',
            options={'permissions': [('can_view_autor', 'Can view autores'), ('can_change_autor', 'Can change autores'), ('can_add_autor', 'Can add autores'), ('can_delete_autor', 'Can delete autores')], 'verbose_name': 'Obra', 'verbose_name_plural': 'Obras'},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'permissions': [('can_view_pessoa', 'Can view pessoas'), ('can_change_pessoa', 'Can change pessoas'), ('can_add_pessoa', 'Can add pessoas'), ('can_delete_pessoa', 'Can delete pessoas')], 'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AddField(
            model_name='obra',
            name='datacadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de registro da obra'),
            preserve_default=False,
        ),
    ]
