# Generated by Django 4.2.7 on 2023-11-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibpub', '0005_alter_autor_options_alter_editora_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editora',
            options={'permissions': [('can_view_editora', 'Can view editoras'), ('can_change_editora', 'Can change editoras'), ('can_add_editora', 'Can add editoras'), ('can_delete_editora', 'Can delete editoras')], 'verbose_name': 'Editora', 'verbose_name_plural': 'Editoras'},
        ),
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'permissions': [('can_view_emprestimo', 'Can view emprestimos'), ('can_change_emprestimo', 'Can change emprestimos'), ('can_add_emprestimo', 'Can add emprestimos'), ('can_delete_emprestimo', 'Can delete emprestimos')], 'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimos'},
        ),
        migrations.AlterModelOptions(
            name='obra',
            options={'permissions': [('can_view_obra', 'Can view obras'), ('can_change_obra', 'Can change obras'), ('can_add_obra', 'Can add obras'), ('can_delete_obra', 'Can delete obras')], 'verbose_name': 'Obra', 'verbose_name_plural': 'Obras'},
        ),
        migrations.AlterField(
            model_name='obra',
            name='datacadastro',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de registro da obra'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='titulo',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Título da obra'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nome'),
        ),
    ]
