# Generated by Django 4.1.5 on 2023-11-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibpub", "0006_alter_editora_options_alter_emprestimo_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="obra",
            options={
                "ordering": ["titulo", "-datacadastro"],
                "permissions": [
                    ("can_view_obra", "Can view obras"),
                    ("can_change_obra", "Can change obras"),
                    ("can_add_obra", "Can add obras"),
                    ("can_delete_obra", "Can delete obras"),
                ],
                "verbose_name": "Obra",
                "verbose_name_plural": "Obras",
            },
        ),
        migrations.AlterField(
            model_name="obra",
            name="isbn",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Número do ISBN da obra",
            ),
        ),
        migrations.AlterField(
            model_name="obra",
            name="issn",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Número do ISSN da obra",
            ),
        ),
    ]
