# Generated by Django 4.1.5 on 2023-11-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bibpub", "0007_alter_obra_options_alter_obra_isbn_alter_obra_issn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editora",
            name="pais",
            field=models.CharField(max_length=100, verbose_name="País da editora"),
        ),
    ]
