# Generated by Django 4.2.7 on 2023-11-25 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibpub', '0008_alter_editora_pais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='data_emprest',
            new_name='dataemprest',
        ),
        migrations.AddField(
            model_name='obra',
            name='dataatualizacao',
            field=models.DateTimeField(auto_now_add=True, default='2023-11-25 18:40:55.346', verbose_name='Data de modificação no registro da obra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obra',
            name='quantidade',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quantidade de unidades'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibpub.pessoa', verbose_name='Pessoa'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibpub.autor', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibpub.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='editora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibpub.editora', verbose_name='Editora'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='tipo',
            field=models.CharField(choices=[('LIVRO', 'Livro'), ('PERIÓDICO', 'Periódico'), ('JORNAL', 'Jornal'), ('REVISTA', 'Revista')], max_length=10, verbose_name='Tipo de obra'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='origem',
            field=models.CharField(choices=[('INTERNET', 'Internet'), ('APLICAÇÃO', 'Aplicação')], default='PENDENTE', max_length=10, verbose_name='Origem do cadastro da pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='situacaocadastro',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('PENDENTE', 'Pendente'), ('SUSPENSO', 'Suspenso'), ('BLOQUEADO', 'Bloqueado')], default='INTERNET', max_length=10, verbose_name='Situação do cadastro da pessoa'),
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilidade', models.CharField(choices=[('INTERNO', 'Interno'), ('INDISPONÍVEL', 'Indisponível'), ('EMPRÉSTIMO', 'Empréstimo')], max_length=15)),
                ('datainclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data de inclusão da unidade da obra')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibpub.obra', verbose_name='Obra')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'db_table': 'tb_unidade',
                'ordering': ['disponibilidade', '-datainclusao'],
                'permissions': [('can_view_unidade', 'Can view unidades'), ('can_change_unidade', 'Can change unidades'), ('can_add_unidade', 'Can add unidades'), ('can_delete_unidade', 'Can delete unidades')],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacaoreserva', models.CharField(default='ATIVA', max_length=10)),
                ('datareserva', models.DateTimeField(auto_now_add=True, verbose_name='Data da reserva')),
                ('obra', models.ManyToManyField(to='bibpub.obra', verbose_name='Obra')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibpub.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'tb_reserva',
                'permissions': [('can_view_reserva', 'Can view reservas'), ('can_change_reserva', 'Can change reservas'), ('can_add_reserva', 'Can add reservas'), ('can_delete_reserva', 'Can delete reservas')],
            },
        ),
    ]
