# Generated by Django 4.2.7 on 2023-11-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibpub', '0009_rename_data_emprest_emprestimo_dataemprest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='edicao',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='unidade',
            name='edicao',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Número da edição da obra'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='genero',
            field=models.IntegerField(choices=[(1, 'Cisgênero'), (2, 'Transgênero'), (3, 'Transexual'), (4, 'Travesti'), (5, 'Gênero fluido'), (6, 'Agênero'), (7, 'Outra'), (8, 'Não informado')], default=8, verbose_name='Identidade de Gênero'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='origem',
            field=models.CharField(choices=[('INTERNET', 'Internet'), ('APLICAÇÃO', 'Aplicação')], default='INTERNET', max_length=10, verbose_name='Origem do cadastro da pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='situacaocadastro',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('PENDENTE', 'Pendente'), ('SUSPENSO', 'Suspenso'), ('BLOQUEADO', 'Bloqueado')], default='PENDENTE', max_length=10, verbose_name='Situação do cadastro da pessoa'),
        ),
    ]
