# Generated by Django 4.2.7 on 2023-11-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibpub', '0010_remove_obra_edicao_remove_obra_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='descricao',
            field=models.TextField(max_length=4000, null=True, verbose_name='Resumo da obra'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='disponibilidade',
            field=models.CharField(choices=[('INTERNO', 'Interno'), ('INDISPONÍVEL', 'Indisponível'), ('EMPRÉSTIMO', 'Empréstimo')], max_length=15, verbose_name='Disponibilidade da unidade da obra'),
        ),
    ]
