# Generated by Django 4.2.7 on 2023-11-28 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibpub', '0011_obra_descricao_alter_unidade_disponibilidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True, verbose_name='Código do país')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome do país')),
                ('datainicial', models.DateField(verbose_name='Data de início')),
                ('datafinal', models.DateField(null=True, verbose_name='Data de término')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'tb_pais',
                'permissions': [('can_view_pais', 'Can view paises'), ('can_change_pais', 'Can change paises'), ('can_add_pais', 'Can add paises'), ('can_delete_pais', 'Can delete paises')],
            },
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='eMail',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='editora',
            name='email',
            field=models.CharField(max_length=254, verbose_name='E-Mail editora'),
        ),
        migrations.AlterField(
            model_name='editora',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibpub.pais', verbose_name='País'),
        ),
    ]
