# Generated by Django 4.2.7 on 2023-11-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibpub', '0013_alter_reserva_options_alter_pessoa_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='origem',
            field=models.CharField(choices=[('INTERNET', 'Internet'), ('APLICAÇÃO', 'Aplicação')], default='INTERNET', max_length=10, verbose_name='Origem do cadastro'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='situacaocadastro',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('PENDENTE', 'Pendente'), ('SUSPENSO', 'Suspenso'), ('BLOQUEADO', 'Bloqueado')], default='PENDENTE', max_length=10, verbose_name='Situação do cadastro'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='datainclusao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de inclusão'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='disponibilidade',
            field=models.CharField(choices=[('INTERNO', 'Interno'), ('INDISPONIVEL', 'Indisponivel'), ('EMPRESTIMO', 'Emprestimo')], default='EMPRESTIMO', max_length=15, verbose_name='Disponibilidade da unidade da obra'),
        ),
    ]
