# Generated by Django 4.2.7 on 2023-12-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibpub', '0015_alter_categoria_descricao_alter_pais_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='situacaocadastro',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('BLOQUEADO', 'Bloqueado')], default='PENDENTE', max_length=10, verbose_name='Situação do cadastro'),
        ),
    ]
