# Generated by Django 4.2.7 on 2023-12-07 03:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibpub', '0016_alter_pessoa_situacaocadastro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['pessoa', '-datareserva'], 'permissions': [('can_view_reserva', 'Can view reservas'), ('can_change_reserva', 'Can change reservas'), ('can_add_reserva', 'Can add reservas'), ('can_delete_reserva', 'Can delete reservas')], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.RenameField(
            model_name='emprestimo',
            old_name='data_devol',
            new_name='datadevol',
        ),
        migrations.AlterField(
            model_name='obra',
            name='dataatualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de modificação no registro da obra'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.CharField(max_length=254, validators=[django.core.validators.EmailValidator(allowlist=None, code=None, message='Informe um e-mail válido!')], verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='uf',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='datareserva',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 0, 14, 52, 430465), verbose_name='Data da reserva'),
        ),
    ]
