# Generated by Django 4.2.7 on 2023-12-15 23:08

import bibpub.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibpub', '0017_alter_reserva_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nascimento',
            field=models.DateField(null=True, validators=[bibpub.validators.NascimentoValidator(menorIdade=5, message='Informe uma data de nascimento válida!')], verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='datareserva',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 15, 20, 8, 34, 273788), verbose_name='Data da reserva'),
        ),
    ]
